accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view, signup_view

app_name = 'accounts'

urlpatterns = [
	path('login/', login_view, name='login'),
	path('logout/', logout_view, name='logout'),
	path('signup/', signup_view, name='signup'),
]

airwatch/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from dashboard.views import main_page_view, home_page_view

urlpatterns = [
	path('', main_page_view, name='main-page'),
	path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', login_required(home_page_view), name='home'),
]

workspaces/urls.py
from django.urls import path

app_name = 'workspaces'

urlpatterns = [
	
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

# Create your models here.

class CustomAccountManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')

		user = self.model(
			email = self.normalize_email(email),
			username=username
		)	

		user.set_password(password)
		user.save()

		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			username=username,
			password=password
		)

		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save()

		return user	

class Account(AbstractBaseUser, PermissionsMixin):
	email = models.EmailField(verbose_name='email', max_length=60, unique=True)
	username = models.CharField(max_length=30, unique=True)
	date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
	is_admin = models.BooleanField(default=False)
	is_staff = models.BooleanField(default=False)
	is_active = models.BooleanField(default=True)
	is_superuser = models.BooleanField(default=False)

	objects = CustomAccountManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username']

	def __str__(self):
		return self.username

	def has_module_perms(self, app_label):
		return True	

dashboard/models.py
from django.db import models

# Create your models here.

workspaces/models.py
from django.db import models
from accounts.models import Account

class Project(models.Model):
	name = models.CharField(max_length=255)
	owner = models.ForeignKey(Account, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.name

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import Account
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.contrib.admin.widgets import FilteredSelectMultiple    
from django.contrib.auth.models import Group

class AccountAuthenticationForm(forms.ModelForm):
	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError('Incorrect email/password')

class CreateUserForm(UserCreationForm):
	email = forms.EmailField(max_length=60, help_text='Incorrect email/password')

	class Meta:
		model = Account
		fields = ('email', 'username', 'password1', 'password2', )

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Account.DoesNotExist:
			return email
		raise forms.ValidationError('An account with this email already exists')

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username
		raise forms.ValidationError('Provided username isn\'t available')

accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from accounts.forms import AccountAuthenticationForm, CreateUserForm
from django.core.exceptions import ValidationError
from accounts.models import Account

def login_view(request, *args, **kwargs):
	context = {}

	user = request.user

	if user.is_authenticated:
		return redirect('home')
	
	form = AccountAuthenticationForm()
	destination = get_redirect_if_exists(request)

	if request.POST:
		form = AccountAuthenticationForm(request.POST)
		if form.is_valid():
			email = request.POST['email']
			password = request.POST['password']
			user = authenticate(email=email, password=password)

			if user:
				request.session['user_id'] = user.id
				request.session['username'] = user.username
				
				login(request, user)
				if destination:
					return redirect(destination)
				else:
					return redirect('home')

	context['login_form'] = form
	return render(request, 'accounts/login.html', context)	

def logout_view(request):
	logout(request)
	return redirect('accounts:login')

def signup_view(request, *args, **kwargs):
	user = request.user

	if user.is_authenticated:
		return redirect('home')	

	context = {}

	if request.POST:
		form = CreateUserForm(request.POST)

		if form.is_valid():
			form.save()
			email = form.cleaned_data.get('email').lower()
			raw_password = form.cleaned_data.get('password1')
			account = authenticate(email=email, password=raw_password)
			login(request, account)

			return redirect('home')
		else:
			context['signup_form'] = form

	else:			
		form = CreateUserForm()
		context['signup_form'] = form

	return render(request, 'accounts/signup.html', context)	

def get_redirect_if_exists(request):
	redirect = None
	if request.GET:
		if request.GET.get("next"):
			redirect = str(request.GET.get("next"))
	return redirect

dashboard/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

from workspaces.models import Project

@require_http_methods(['GET'])
def main_page_view(request):
	return render(request, 'dashboard/index.html', {})

@require_http_methods(['GET'])
def home_page_view(request):
	user = request.user

	projects = Project.objects.filter(
		owner__id=user.id
	).values('id', 'name')

	context = {
		'projects': projects
	}

	return render(request, 'dashboard/dashboard.html', context)	

workspaces/views.py
from django.shortcuts import render

# Create your views here.

templates/accounts/login.html
{% extends 'common/base.html' %}
{% block title %} AirWatch - Home {% endblock %}
{% block content %}
{% load static %}		
<div class='bg-image'>
	<div class='p-3 bg-text font-weight-bold'>
		<h1><a href='{% url "main-page" %}' class='logo'>AirWatch</a></h1>
		<div class="row d-flex justify-content-center align-items-center h-100 mt-5">
			<div class="col-12 col-md-8 col-lg-6 col-xl-5">
				<div class='card shadow'>
					<div class="card-body p-5">
						<h3 class="fw-bold mb-2 text-black">Sign In</h3>
						<form class='mt-4' method='POST'>
							{% csrf_token %}
							<input type="text" id="inputEmail" name='email' class="form-control" placeholder="Email" autofocus required>
							<div class='input-group mt-3 mb-4'>
								<input type="password" id="inputPassword" name='password' class="form-control" placeholder="Hasło" required>
							</div>
							{% for field in login_form %}	
							<p>
							{% for error in field.errors %}
								<p class='text-danger'>{{ error }}</p>
							{% endfor %}
							</p>
							{% endfor %}
							{% if login_form.non_field_errors %}
							<div class='text-danger'>
								<p>{{login_form.non_field_errors}}</p>
							</div>
							{% endif %}
							<button class="btn btn-navy w-100" type="submit" value="Login">Login</button>
						</form>	
					</div>	
				</div>
			</div>	
		</div>		
	</div>	
</div>	
{% endblock %}

templates/accounts/signup.html
{% extends 'common/base.html' %}
{% block title %} AirWatch - Home {% endblock %}
{% block content %}
{% load static %}		
<div class='bg-image'>
	<div class='p-3 bg-text font-weight-bold'>
		<h1><a href='{% url "main-page" %}' class='logo'>AirWatch</a></h1>
		<div class="row d-flex justify-content-center align-items-center h-100 mt-5">
			<div class="col-12 col-md-8 col-lg-6 col-xl-5">
				<div class='card shadow'>
					<div class="card-body p-5">
						<h3 class="fw-bold mb-2 text-black">Sign Up</h3>
						<form class='mt-4' method="post">
							{% csrf_token %}
							<input type="email" name="email" id="inputEmail" class="form-control mt-3"
							placeholder="Email address" required autofocus>
							<input type="text" name="username" id="inputUsername" class="form-control mt-3" placeholder="Username" required>
							<input type="password" name="password1" id="inputPassword1" class="form-control mt-3" placeholder="Password" required>
							<input type="password" name="password2" id="inputPassword2" class="form-control mt-3"
							 placeholder="Confirm password" required>
							{% for field in signup_form %}
							<p>
							{% for error in field.errors %}
							<p class='text-danger'>{{ error }}</p>
							{% endfor %}
							</p>
							{% endfor %}
							{% if registration_form.non_field_errors %}
							<div class='text-danger'>
								<p>{{registration_form.non_field_errors}}</p>
							</div>

							{% endif %}
							<div class='text-center'>
								<button class="btn btn-lg btn-navy btn-block mt-3" type="submit">Continue</button>	
							</div>	
						</form>	
					</div>	
				</div>	
			</div>	
		</div>	
	</div>	
</div>	
{% endblock %}

templates/common/base.html
{% load static %}
<!doctype html>
<html lang="en-gb">   
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontello/css/fontello.css' %}">
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>

    <title>{% block title %}  {% endblock %}</title>
  </head>
  <body>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block content %}
    {% endblock %}
  </body>
</html>

templates/common/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-purple">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href='{% url "home" %}'><h2>AirWatch</h2></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href='{% url "home" %}'><i class='icon-gauge'></i> Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class='icon-user'></i> My Account
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#"><i class='icon-pencil'></i> Edit Profile</a></li>
            <li><a class="dropdown-item" href="#"><i class='icon-key'></i> Change Password</a></li>
            <li><a class="dropdown-item" href='{% url "accounts:logout" %}'><i class='icon-logout'></i> Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/dashboard/dashboard.html
{% extends 'common/base.html' %}
{% block title %} AirWatch - Start {% endblock %}
{% block content %}
{% include 'common/nav.html' %}
<div class='container'>
	<div class='row mt-3'>
		<div class='col-lg-4 col-md-6 col-sm-12'>
			<div class='card shadow border-0'>
				<div class='card-header bg-purple'>
					<div class='d-flex pt-2'>
						<h4 class='text-white pr-4'>My Projects</h4>
						<a class='btn btn-purple shadow' href='#'>New Project +</a>
					</div>
				</div>
				<div class='card-body bg-gray'>
					{% for project in projects %}
					<a href='#'>{{ project.name }}</a>
					{% empty %}
					<div class='text-white-50'>
						You have no current projects
					</div>	
					{% endfor %}
				</div>	
			</div>		
		</div>
		<div class='col-lg-4 col-md-6 col-sm-12'>
			asdf
		</div>
		<div class='col-lg-4 col-md-6 col-sm-12'>
			asdf
		</div>	
	</div>	
</div>
{% endblock %}

templates/dashboard/index.html
{% extends 'common/base.html' %}
{% block title %} AirWatch - Home {% endblock %}
{% block content %}
{% load static %}		
<div class='bg-image'>
	<div class='p-3 bg-text font-weight-bold'>
		<h1><a href='{% url "main-page" %}' class='logo'>AirWatch</a></h1>
		<div class='text-center mt-5'>
			<h3 class='pt-4'>Satellite Insights for Clean Air – Analyse, Compare, Breathe Easy!</h3>
			<div class='d-flex justify-content-center mt-5'>
				<a class='btn btn-login px-4 shadow' href='{% url "accounts:login" %}'>Sign In</a>
				<a class='btn btn-signup px-4 pt-2 shadow' href='{% url "accounts:signup" %}'>Get Started</a>
			</div>
			<h4 class='pt-4 mt-5'>Powered by Sentinel-5P data</h4>	
		</div>		
	</div>	
</div>	
{% endblock %}